# Generated by Django 4.2.4 on 2023-09-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('about', models.CharField(max_length=300)),
                ('website', models.URLField(max_length=150)),
            ],
        ),
    ]
