# Generated by Django 4.2.4 on 2023-09-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_movie_plateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plateform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='app.streamplateform'),
        ),
    ]
