# Generated by Django 4.2.4 on 2023-09-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plateform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='app.streamplateform'),
        ),
    ]
