# Generated by Django 4.2.4 on 2023-10-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_review_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avrg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
